version: '3.8'
services:
  client-react:
    env_file:
      - .env
    build:
      context: ./client-react
      dockerfile: Dockerfile
    command: yarn dev
    ports:
      - "${AIS_CLIENT_REACT_PORT}:${AIS_CLIENT_REACT_PORT}"
