version: '3.8'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: tmp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database-mysql:/docker-entrypoint-initdb.d
    ports:
      - "${DATABASE_MYSQL_PORT}:3306"

  server-grpc-go:
    env_file:
      - .env
    build:
      context: ./server-grpc-go
      dockerfile: Dockerfile
    ports:
      - "${SERVER_GRPC_GO_PORT}:${SERVER_GRPC_GO_PORT}"

  server-grpc-envoy-go:
    env_file:
      - .env
    build:
      context: ./server-grpc-envoy-go
      dockerfile: Dockerfile
    ports:
      - "${SERVER_GRPC_ENVOY_GO_PORT}:${SERVER_GRPC_ENVOY_GO_PORT}"
