version: '3.8'
services:
  interface-grpc-environment-go:
    command: /work/interface-grpc/environment-go/generate.sh
    build:
      context: ./interface-grpc/environment-go
      dockerfile: Dockerfile
    volumes:
      - .:/work
  interface-grpc-environment-java:
    command: /work/interface-grpc/environment-java/generate.sh
    build:
      context: ./interface-grpc/environment-java
      dockerfile: Dockerfile
    volumes:
      - .:/work
