version: '3.8'
services:
  database-mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: database-mysql
    environment:
      MYSQL_DATABASE: tmp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "${TZ}"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database-mysql:/docker-entrypoint-initdb.d
    ports:
      - "${AIS_DATABASE_MYSQL_PORT}:3306"

  server-go-grpc:
    env_file:
      - .env
    build:
      context: ./server-go-grpc
      dockerfile: Dockerfile
    ports:
      - "${AIS_SERVER_GO_GRPC_PORT}:${AIS_SERVER_GO_GRPC_PORT}"
    depends_on:
      - database-mysql

  server-go-grpc-envoy:
    env_file:
      - .env
    build:
      context: ./server-go-grpc-envoy
      dockerfile: Dockerfile
    ports:
      - "${AIS_SERVER_GO_GRPC_ENVOY_PORT}:${AIS_SERVER_GO_GRPC_ENVOY_PORT}"
    depends_on:
      - database-mysql
