version: '3.8'
services:
  client-react:
    env_file:
      - .env
    build:
      context: ./client-react
      dockerfile: Dockerfile
    command: yarn start -p ${CLIENT_REACT_PORT}
    ports:
      - "${CLIENT_REACT_PORT}:${CLIENT_REACT_PORT}"
