/**
 * @fileoverview gRPC-Web generated client stub for sample
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.12.4
// source: interface-grpc/chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as interface$grpc_chat_pb from '../interface-grpc/chat_pb';


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPost = new grpcWeb.MethodDescriptor(
    '/sample.ChatService/Post',
    grpcWeb.MethodType.UNARY,
    interface$grpc_chat_pb.PostRequest,
    google_protobuf_empty_pb.Empty,
    (request: interface$grpc_chat_pb.PostRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  post(
    request: interface$grpc_chat_pb.PostRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  post(
    request: interface$grpc_chat_pb.PostRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  post(
    request: interface$grpc_chat_pb.PostRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sample.ChatService/Post',
        request,
        metadata || {},
        this.methodDescriptorPost,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sample.ChatService/Post',
    request,
    metadata || {},
    this.methodDescriptorPost);
  }

  methodDescriptorGet = new grpcWeb.MethodDescriptor(
    '/sample.ChatService/Get',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    interface$grpc_chat_pb.GetResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    interface$grpc_chat_pb.GetResponse.deserializeBinary
  );

  get(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<interface$grpc_chat_pb.GetResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/sample.ChatService/Get',
      request,
      metadata || {},
      this.methodDescriptorGet);
  }

}

